#!/bin/bash

echo "Running prepare-commit-msg script..."
echo "Commit message file: $1"

if [ ! -f "$1" ]; then
  echo "Commit message file not found!"
  exit 1
fi

jira-prepare-commit-msg "$1"

TICKET_ID=$(grep -oP 'GN-\d+' "$1")

if [ -n "$TICKET_ID" ]; then
   	sed -i 's/\[GN-[0-9]*\]//g' "$1"
		sed -i "s/^\(.*\): \(.*\)$/\1($TICKET_ID): \2/" "$1"
else
    echo "No ticket ID found."
fi

sed -i 's/^[ \t]*//;s/[ \t]*$//' "$1"

echo "Script finished."
